@set allusersprofile=c:\programdata
@set appdata=c:\users\hp15eq\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=desktop-brafnul
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set efc_9312=1
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set external_include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.22621.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\fsharp\tools
@set gcexpconfigusedinsession=3
@set graalvm_home=d:\graalvm\graalvm-ce-java11-20.3.2
@set homedrive=c:
@set homepath=\users\hp15eq
@set include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.22621.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.22621.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set intellij idea community edition=d:\program files\jetbrains\intellij idea community edition 2022.3.2\bin
@set java_home=c:\program files\java\jdk-20\bin
@set lib=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.22621.0\ucrt\x64;c:\program files (x86)\windows kits\10\\lib\10.0.22621.0\\um\x64
@set libpath=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.22621.0;c:\program files (x86)\windows kits\10\references\10.0.22621.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\hp15eq\appdata\local
@set logonserver=\\desktop-brafnul
@set maven_home=d:\maven\bin
@set msbuilddisablefeaturesfromversion=17.6
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=4
@set onedrive=c:\users\hp15eq\onedrive
@set os=windows_nt
@set path=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\bin\hostx64\x64;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\vcpackages;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files\microsoft visual studio\2022\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\fsharp\tools;c:\program files\microsoft visual studio\2022\community\team tools\diagnosticshub\collector;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\\x64;c:\program files (x86)\windows kits\10\bin\\x64;c:\program files\microsoft visual studio\2022\community\\msbuild\current\bin\amd64;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files\microsoft visual studio\2022\community\common7\ide\;c:\program files\microsoft visual studio\2022\community\common7\tools\;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\nodejs\;c:\program files\wireguard\;c:\program files\putty\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\cmake\bin;c:\program files\git\cmd;c:\program files\dotnet\;d:\applications\vcpkg\;c:\users\hp15eq\appdata\local\microsoft\windowsapps;c:\users\hp15eq\appdata\local\githubdesktop\bin;d:\program files\jetbrains\intellij idea community edition 2022.3.2\bin;c:\users\hp15eq\appdata\roaming\npm;c:\users\hp15eq\appdata\local\programs\microsoft vs code\bin;c:\msys64\ucrt64\bin;c:\msys64\ucrt64\bin\python.exe;c:\users\hp15eq\.dotnet\tools;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\linux\bin\connectionmanagerexe;c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\hp15eq\appdata\local\microsoft\visualstudio\17.0_57f1111d\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=amd64 family 23 model 24 stepping 1, authenticamd
@set processor_level=23
@set processor_revision=1801
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2022=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_installdir_vs2022=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_netcoresdkmajorversion=8
@set pvsbuildtools_vctargetspath_current=c:\program files\microsoft visual studio\2022\community\msbuild\microsoft\vc\v170\
@set pvsbuildtools_visualstudioversion_current=17.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\8.0.302\sdks
@set servicehublogsessionkey=7759e0b2
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\hp15eq\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\hp15eq\appdata\local\temp
@set ucrtversion=10.0.22621.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-brafnul
@set userdomain_roamingprofile=desktop-brafnul
@set username=hp15eq
@set userprofile=c:\users\hp15eq
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcideinstalldir=c:\program files\microsoft visual studio\2022\community\common7\ide\vc\
@set vcinstalldir=c:\program files\microsoft visual studio\2022\community\vc\
@set vcpg_root=d:\applications\vcpkg
@set vcpkg_root=c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set vctoolsinstalldir=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\
@set vctoolsredistdir=c:\program files\microsoft visual studio\2022\community\vc\redist\msvc\14.40.33807\
@set vctoolsversion=14.40.33807
@set visualstudiodir=c:\users\hp15eq\documents\visual studio 2022
@set visualstudioedition=microsoft visual studio community 2022
@set visualstudioversion=17.0
@set vs170comntools=c:\program files\microsoft visual studio\2022\community\common7\tools\
@set vsappiddir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=17.10.3
@set vsinstalldir=c:\program files\microsoft visual studio\2022\community\
@set vslang=1033
@set vspermonitordpiawarenessenabled.2024=true
@set vsskuedition=community
@set vs_perf_session_gcheapcount=2
@set webview2_default_background_color=ffffff
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.22621.0;c:\program files (x86)\windows kits\10\references\10.0.22621.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.22621.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.22621.0\
@set windowssdkversion=10.0.22621.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.40.33807\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22621.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\nodejs\;c:\program files\wireguard\;c:\program files\putty\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\cmake\bin;c:\program files\git\cmd;c:\program files\dotnet\;d:\applications\vcpkg\;c:\users\hp15eq\appdata\local\microsoft\windowsapps;c:\users\hp15eq\appdata\local\githubdesktop\bin;d:\program files\jetbrains\intellij idea community edition 2022.3.2\bin;c:\users\hp15eq\appdata\roaming\npm;c:\users\hp15eq\appdata\local\programs\microsoft vs code\bin;c:\msys64\ucrt64\bin;c:\msys64\ucrt64\bin\python.exe;c:\users\hp15eq\.dotnet\tools

@call "cl.exe" @"D:\Applications\FBCountLib\FamilyBudgetCountLib\main.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1